trigger:
    branches:
        include:
            - main

pool:
    vmImage: 'ubuntu-latest'


variables:
    IMAGE_NAME: 'monitoring'
    DOCKER_REGISTRY: 'docker.io'
    DOCKER_TAG: '$(Build.BuildId)'

stages:
    - stage: Build
      displayName: Build Docker Image
      jobs:
      - job: Dockerbuild
        displayName: Build Job
        steps:
            - task: UsePythonVersion@0
              inputs:
                versionSpec: '3.x'

            - task: Checkout@1

            - script: |
                pip install -r requirements.txt
              displayName: Install dependencies

            - script: |
               pytest tests/
              displayName: Run unit test

            - script: |
                echo "Build Docker image..."
                docker build -t $(IMAGE_NAME):$(DOCKER_TAG) .
              displayName: Build Docker IMage
            - script: |
                echo "Docker Images List"
                docker images
              displayName: Images list
